# Generated by Django 5.1.5 on 2025-03-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2blead',
            name='meeting_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='status',
            field=models.CharField(choices=[('Meeting Scheduled', 'Meeting Scheduled'), ('Client Visit', 'Client Visit'), ('Kitchen Visit', 'Kitchen Visit'), ('Sampling', 'Sampling'), ('Menu & Price Fixed', 'Menu & Price Fixed'), ('Start date confirmed', 'Start date confirmed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='meeting_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
