# Generated by Django 5.1.5 on 2025-03-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0002_alter_b2blead_meeting_date_time_alter_b2blead_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('followup_message', models.TextField()),
                ('followup_status', models.CharField(choices=[('meeting_done', 'Meeting Done'), ('process_hold', 'Process Hold'), ('process_further', 'Process Further'), ('process_finished', 'Process Finished'), ('kitchen_visit_done', 'Kitchen Visit Done'), ('sampling_done', 'Sampling Done'), ('finalized', 'Finalized'), ('date_confirmed', 'Date Confirmed'), ('customer', 'Converted to Customer')], default='meeting_done', max_length=50)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('followup_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='B2CFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('followup_message', models.TextField()),
                ('followup_status', models.CharField(choices=[('meeting_scheduled', 'Meeting Scheduled'), ('meeting_done', 'Meeting Done'), ('menu_price_fixed', 'Menu and Price Fixed'), ('date_confirmed', 'Date Confirmed'), ('payment_done', 'Payment Done'), ('customer', 'Converted to Customer')], default='meeting_scheduled', max_length=50)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('followup_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='b2clead',
            old_name='required_model_service',
            new_name='required_meal_service',
        ),
        migrations.AddField(
            model_name='b2blead',
            name='dietary_options',
            field=models.CharField(choices=[('Vegetarian', 'Veg'), ('Non_Vegetarian', 'Non_Veg'), ('Vegan', 'Vegan')], default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='b2clead',
            name='dietary_options',
            field=models.CharField(choices=[('Vegetarian', 'Veg'), ('Non_Vegetarian', 'Non_Veg'), ('Vegan', 'Vegan')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='status',
            field=models.CharField(choices=[('Meeting Scheduled', 'Meeting Scheduled'), ('Meeting not Scheduled', 'Meeting not Scheduled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='status',
            field=models.CharField(choices=[('Meeting Scheduled', 'Meeting Scheduled'), ('Meeting not Scheduled', 'Meeting not Scheduled')], max_length=50),
        ),
    ]
