# Generated by Django 5.1.5 on 2025-03-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0007_alter_b2blead_company_name_alter_b2blead_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2blead',
            name='required_meal_service',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Tea & Snacks', 'Tea & Snacks'), ('Supper', 'Supper'), ('All', 'All')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='service_choice',
            field=models.CharField(blank=True, choices=[('Just delivery', 'Just delivery'), ('Buffet', 'Buffet'), ('With Service Person', 'With Service Person')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='service_type',
            field=models.CharField(blank=True, choices=[('In_house', 'In_house'), ('Outsource', 'Outsource')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='status',
            field=models.CharField(blank=True, choices=[('Meeting Scheduled', 'Meeting Scheduled'), ('Meeting not Scheduled', 'Meeting not Scheduled'), ('Not Interested', 'Not Interested')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='delivery_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='event_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='required_meal_service',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks'), ('Hi_tea', 'Hi_tea')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='service_choice',
            field=models.CharField(blank=True, choices=[('Just delivery', 'Just delivery'), ('Buffet', 'Buffet'), ('With Service Person', 'With Service Person')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='status',
            field=models.CharField(blank=True, choices=[('Meeting Scheduled', 'Meeting Scheduled'), ('Meeting not Scheduled', 'Meeting not Scheduled')], max_length=50, null=True),
        ),
    ]
