# Generated by Django 5.1.5 on 2025-03-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0008_alter_b2blead_required_meal_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C')], max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
