# Generated by Django 5.1.5 on 2025-03-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0009_makelead'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2blead',
            name='call_id',
            field=models.CharField(default='Unknown', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='b2clead',
            name='call_id',
            field=models.CharField(default='Unknown', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='makelead',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('PENDING', 'PENDING'), ('CALLED_B2B', 'CALLED_B2B'), ('CALLED_B2C', 'CALLED_B2C')], max_length=255, null=True),
        ),
    ]
