# Generated by Django 5.1.5 on 2025-03-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0010_b2blead_call_id_b2clead_call_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2blead',
            name='call_id',
            field=models.CharField(default='Null', max_length=255, unique=True),
        ),
    ]
