# Generated by Django 5.1.5 on 2025-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0011_alter_b2blead_call_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2blead',
            name='call_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='call_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
