# Generated by Django 5.1.5 on 2025-03-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0012_alter_b2blead_call_id_alter_b2clead_call_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makelead',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='makelead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='makelead',
            name='event_type',
        ),
        migrations.AddField(
            model_name='makelead',
            name='count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='makelead',
            name='type',
            field=models.CharField(choices=[('CORPORATE', 'CORPORATE'), ('INDIVIDUAL', 'INDIVIDUAL')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='makelead',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('PENDING', 'PENDING'), ('ATTENDED', 'ATTENDED')], max_length=255, null=True),
        ),
    ]
