# Generated by Django 5.1.5 on 2025-03-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0013_rename_address_makelead_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makelead',
            old_name='company_name',
            new_name='org_name',
        ),
    ]
