# Generated by Django 5.1.5 on 2025-03-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0014_rename_company_name_makelead_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2blead',
            name='lead_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2clead',
            name='lead_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='call_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
