# Generated by Django 5.1.5 on 2025-03-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0015_b2blead_lead_score_b2clead_lead_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2blead',
            name='event_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
