# Generated by Django 5.1.5 on 2025-03-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0016_b2blead_event_date_time_alter_b2blead_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InpersonLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('lead_generater_name', models.CharField(max_length=225)),
                ('source_comefrom', models.CharField(max_length=225)),
                ('lead_category', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('contact_number', models.CharField(max_length=225)),
                ('alternate_number', models.CharField(blank=True, max_length=225, null=True)),
                ('location', models.CharField(max_length=225)),
                ('head_count', models.CharField(max_length=225)),
                ('required_meal_service', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Tea & Snacks', 'Tea & Snacks'), ('Supper', 'Supper'), ('All', 'All')], max_length=50)),
                ('event_type', models.CharField(choices=[('Industrial', 'Industrial'), ('Corporate', 'Corporate'), ('Bussiness_Event', 'Bussiness_Event'), ('', '')], max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('designation', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('In_house', 'In_house'), ('Outsource', 'Outsource')], max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('event_date_time', models.DateTimeField()),
                ('choice_of_menu', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PENDING', 'PENDING'), ('ATTENDED', 'ATTENDED')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OutsorceDBLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=225, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('mail_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PENDING', 'PENDING'), ('ATTENDED', 'ATTENDED')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='MakeLead',
        ),
        migrations.RemoveField(
            model_name='b2blead',
            name='event_date_time',
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='count',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='delivery_location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='lead_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='required_meal_service',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Tea & Snacks', 'Tea & Snacks'), ('Supper', 'Supper'), ('All', 'All')], max_length=50),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='service_choice',
            field=models.CharField(choices=[('Just delivery', 'Just delivery'), ('Buffet', 'Buffet'), ('With Service Person', 'With Service Person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='service_type',
            field=models.CharField(choices=[('In_house', 'In_house'), ('Outsource', 'Outsource')], max_length=50),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='status',
            field=models.CharField(choices=[('Meeting Scheduled', 'Meeting Scheduled'), ('Meeting not Scheduled', 'Meeting not Scheduled'), ('Not Interested', 'Not Interested')], max_length=50),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='call_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='contact_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='delivery_location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='dietary_options',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non_Veg', 'Non_Veg'), ('Vegan', 'Vegan')], default='Unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='event_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='lead_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='meeting_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='required_meal_service',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks'), ('Hi_tea', 'Hi_tea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='service_choice',
            field=models.CharField(choices=[('Just delivery', 'Just delivery'), ('Buffet', 'Buffet'), ('With Service Person', 'With Service Person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='status',
            field=models.CharField(choices=[('Meeting Scheduled', 'Meeting Scheduled'), ('Meeting not Scheduled', 'Meeting not Scheduled')], max_length=50),
        ),
    ]
