# Generated by Django 5.1.5 on 2025-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0017_inpersonlead_outsorcedblead_delete_makelead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2blead',
            name='service_choice',
            field=models.CharField(blank=True, choices=[('Just delivery', 'Just delivery'), ('Buffet', 'Buffet'), ('With Service Person', 'With Service Person')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='service_type',
            field=models.CharField(blank=True, choices=[('In_house', 'In_house'), ('Outsource', 'Outsource')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='dietary_options',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non_Veg', 'Non_Veg'), ('Vegan', 'Vegan')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='service_choice',
            field=models.CharField(blank=True, choices=[('Just delivery', 'Just delivery'), ('Buffet', 'Buffet'), ('With Service Person', 'With Service Person')], max_length=50, null=True),
        ),
    ]
