# Generated by Django 5.1.5 on 2025-03-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0018_alter_b2blead_service_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2blead',
            name='status',
            field=models.CharField(choices=[('Meeting Scheduled', 'Meeting Scheduled'), ('Meeting not Scheduled', 'Meeting not Scheduled-hold'), ('Not Interested', 'Not Interested')], max_length=50),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='meeting_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
