# Generated by Django 5.1.5 on 2025-03-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_APP', '0019_alter_b2blead_status_alter_b2clead_meeting_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2blead',
            name='lead_status',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='b2clead',
            name='lead_status',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='count',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='delivery_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='dietary_options',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non_Veg', 'Non_Veg'), ('Vegan', 'Vegan')], default='Unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Industrial', 'Industrial'), ('Corporate', 'Corporate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='lead_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='required_meal_service',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Tea & Snacks', 'Tea & Snacks'), ('Supper', 'Supper'), ('All', 'All')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2blead',
            name='status',
            field=models.CharField(blank=True, choices=[('Meeting Scheduled', 'Meeting Scheduled'), ('Meeting not Scheduled', 'Meeting not Scheduled-hold'), ('Not Interested', 'Not Interested')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='delivery_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='dietary_options',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non_Veg', 'Non_Veg'), ('Vegan', 'Vegan')], default='Unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='event_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='required_meal_service',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks'), ('Hi_tea', 'Hi_tea')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2clead',
            name='status',
            field=models.CharField(blank=True, choices=[('Meeting Scheduled', 'Meeting Scheduled'), ('Meeting not Scheduled', 'Meeting not Scheduled')], max_length=50, null=True),
        ),
    ]
